# Generated by Django 5.0.3 on 2024-04-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shows_remove_item_grocery_list_movies_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shows',
        ),
    ]
