# Generated by Django 5.0.3 on 2024-04-23 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_movies_genre_id_remove_shows_genre_id_games'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='user',
        ),
        migrations.AddField(
            model_name='games',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movies',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shows',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
