# Generated by Django 5.0.3 on 2024-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_games_user_remove_movies_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='show_id',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='show_id',
        ),
        migrations.AddField(
            model_name='games',
            name='poster_path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movies',
            name='poster_path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shows',
            name='poster_path',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='games',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shows',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
